name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.environment }}-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        environment: [test-min-versions, test]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.64.0
          cache: true
          environments: ${{ matrix.environment }}

      - name: List installed libraries
        run: |
          pixi install --environment ${{ matrix.environment }}
          pixi list --environment ${{ matrix.environment }}

      - name: Restore test data cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: tests/data
          key: test-data-${{ hashFiles('scripts/github_sources.json') }}

      - name: Download test images
        run: |
          pixi run -e ${{ matrix.environment }} download-test-images

      - name: Save test data cache
        if: matrix.environment == 'test'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: tests/data
          key: test-data-${{ hashFiles('scripts/github_sources.json') }}

      - name: Running Tests
        run: |
          pixi run -e ${{ matrix.environment }} run-tests-xml-cov

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
